### ISSUE TITLE
[PoC] Tab 10개 추가

### ISSUE THREAD

**Issue by msaltnet** [msaltnet/T.Viewer#3]
Viewer tab 10개 추가하고, 단순 메세지 출력 동작 확인

**Comment by msaltnet** [comment]
리눅스 빌드 추가, 릴리스 추가하기
.travis.xml
```
os:
  - linux
  - windows

branches:
  only:
    - master
    - /releases\/.+/

install:
  - npm install

script:
  - npm run lint && npm run build
  - | 
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      npm run dist:linux
    fi
    if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      npm run dist:win
    fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key: 
    secure:
  file_glob: true
  file: 
    - "dist/*.AppImage"
    - "dist/*.exe"
  draft: true
  on:
    branch: master
```
리눅스 추가하기
vue.config.js
```
        linux: {
          target: [
            {
              target: 'AppImage',
              arch: [
                'x64',
              ],
            },
          ],
        },
      },
```
